//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.27 at 09:48:43 PM EST 
//


package com.ptab.sky;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UsPatentGrant }
     * 
     */
    public UsPatentGrant createUsPatentGrant() {
        return new UsPatentGrant();
    }

    /**
     * Create an instance of {@link UsPatentGrant.Abstract }
     * 
     */
    public UsPatentGrant.Abstract createUsPatentGrantAbstract() {
        return new UsPatentGrant.Abstract();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant createUsPatentGrantUsBibliographicDataGrant() {
        return new UsPatentGrant.UsBibliographicDataGrant();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.Examiners }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.Examiners createUsPatentGrantUsBibliographicDataGrantExaminers() {
        return new UsPatentGrant.UsBibliographicDataGrant.Examiners();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.Assignees }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.Assignees createUsPatentGrantUsBibliographicDataGrantAssignees() {
        return new UsPatentGrant.UsBibliographicDataGrant.Assignees();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.Assignees.Assignee }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.Assignees.Assignee createUsPatentGrantUsBibliographicDataGrantAssigneesAssignee() {
        return new UsPatentGrant.UsBibliographicDataGrant.Assignees.Assignee();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.Assignees.Assignee.Addressbook }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.Assignees.Assignee.Addressbook createUsPatentGrantUsBibliographicDataGrantAssigneesAssigneeAddressbook() {
        return new UsPatentGrant.UsBibliographicDataGrant.Assignees.Assignee.Addressbook();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsParties }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsParties createUsPatentGrantUsBibliographicDataGrantUsParties() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsParties();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsParties.Agents }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsParties.Agents createUsPatentGrantUsBibliographicDataGrantUsPartiesAgents() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsParties.Agents();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsParties.Agents.Agent }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsParties.Agents.Agent createUsPatentGrantUsBibliographicDataGrantUsPartiesAgentsAgent() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsParties.Agents.Agent();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsParties.Agents.Agent.Addressbook }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsParties.Agents.Agent.Addressbook createUsPatentGrantUsBibliographicDataGrantUsPartiesAgentsAgentAddressbook() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsParties.Agents.Agent.Addressbook();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsParties.Inventors }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsParties.Inventors createUsPatentGrantUsBibliographicDataGrantUsPartiesInventors() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsParties.Inventors();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsParties.Inventors.Inventor }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsParties.Inventors.Inventor createUsPatentGrantUsBibliographicDataGrantUsPartiesInventorsInventor() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsParties.Inventors.Inventor();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsParties.Inventors.Inventor.Addressbook }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsParties.Inventors.Inventor.Addressbook createUsPatentGrantUsBibliographicDataGrantUsPartiesInventorsInventorAddressbook() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsParties.Inventors.Inventor.Addressbook();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsParties.UsApplicants }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsParties.UsApplicants createUsPatentGrantUsBibliographicDataGrantUsPartiesUsApplicants() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsParties.UsApplicants();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsParties.UsApplicants.UsApplicant }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsParties.UsApplicants.UsApplicant createUsPatentGrantUsBibliographicDataGrantUsPartiesUsApplicantsUsApplicant() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsParties.UsApplicants.UsApplicant();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsParties.UsApplicants.UsApplicant.Addressbook }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsParties.UsApplicants.UsApplicant.Addressbook createUsPatentGrantUsBibliographicDataGrantUsPartiesUsApplicantsUsApplicantAddressbook() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsParties.UsApplicants.UsApplicant.Addressbook();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments createUsPatentGrantUsBibliographicDataGrantUsRelatedDocuments() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.RelatedPublication }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.RelatedPublication createUsPatentGrantUsBibliographicDataGrantUsRelatedDocumentsRelatedPublication() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.RelatedPublication();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.Continuation }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.Continuation createUsPatentGrantUsBibliographicDataGrantUsRelatedDocumentsContinuation() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.Continuation();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.Continuation.Relation }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.Continuation.Relation createUsPatentGrantUsBibliographicDataGrantUsRelatedDocumentsContinuationRelation() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.Continuation.Relation();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.Continuation.Relation.ChildDoc }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.Continuation.Relation.ChildDoc createUsPatentGrantUsBibliographicDataGrantUsRelatedDocumentsContinuationRelationChildDoc() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.Continuation.Relation.ChildDoc();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.Continuation.Relation.ParentDoc }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.Continuation.Relation.ParentDoc createUsPatentGrantUsBibliographicDataGrantUsRelatedDocumentsContinuationRelationParentDoc() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.Continuation.Relation.ParentDoc();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsFieldOfClassificationSearch }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsFieldOfClassificationSearch createUsPatentGrantUsBibliographicDataGrantUsFieldOfClassificationSearch() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsFieldOfClassificationSearch();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsReferencesCited }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsReferencesCited createUsPatentGrantUsBibliographicDataGrantUsReferencesCited() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsReferencesCited();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsReferencesCited.UsCitation }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsReferencesCited.UsCitation createUsPatentGrantUsBibliographicDataGrantUsReferencesCitedUsCitation() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsReferencesCited.UsCitation();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsReferencesCited.UsCitation.Patcit }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsReferencesCited.UsCitation.Patcit createUsPatentGrantUsBibliographicDataGrantUsReferencesCitedUsCitationPatcit() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsReferencesCited.UsCitation.Patcit();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc createUsPatentGrantUsBibliographicDataGrantClassificationsCpc() {
        return new UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.FurtherCpc }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.FurtherCpc createUsPatentGrantUsBibliographicDataGrantClassificationsCpcFurtherCpc() {
        return new UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.FurtherCpc();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.FurtherCpc.ClassificationCpc }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.FurtherCpc.ClassificationCpc createUsPatentGrantUsBibliographicDataGrantClassificationsCpcFurtherCpcClassificationCpc() {
        return new UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.FurtherCpc.ClassificationCpc();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.MainCpc }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.MainCpc createUsPatentGrantUsBibliographicDataGrantClassificationsCpcMainCpc() {
        return new UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.MainCpc();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.MainCpc.ClassificationCpc }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.MainCpc.ClassificationCpc createUsPatentGrantUsBibliographicDataGrantClassificationsCpcMainCpcClassificationCpc() {
        return new UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.MainCpc.ClassificationCpc();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.ClassificationsIpcr }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.ClassificationsIpcr createUsPatentGrantUsBibliographicDataGrantClassificationsIpcr() {
        return new UsPatentGrant.UsBibliographicDataGrant.ClassificationsIpcr();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.ClassificationsIpcr.ClassificationIpcr }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.ClassificationsIpcr.ClassificationIpcr createUsPatentGrantUsBibliographicDataGrantClassificationsIpcrClassificationIpcr() {
        return new UsPatentGrant.UsBibliographicDataGrant.ClassificationsIpcr.ClassificationIpcr();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.ApplicationReference }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.ApplicationReference createUsPatentGrantUsBibliographicDataGrantApplicationReference() {
        return new UsPatentGrant.UsBibliographicDataGrant.ApplicationReference();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.PublicationReference }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.PublicationReference createUsPatentGrantUsBibliographicDataGrantPublicationReference() {
        return new UsPatentGrant.UsBibliographicDataGrant.PublicationReference();
    }

    /**
     * Create an instance of {@link UsPatentGrant.Abstract.P }
     * 
     */
    public UsPatentGrant.Abstract.P createUsPatentGrantAbstractP() {
        return new UsPatentGrant.Abstract.P();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.InventionTitle }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.InventionTitle createUsPatentGrantUsBibliographicDataGrantInventionTitle() {
        return new UsPatentGrant.UsBibliographicDataGrant.InventionTitle();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.Figures }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.Figures createUsPatentGrantUsBibliographicDataGrantFigures() {
        return new UsPatentGrant.UsBibliographicDataGrant.Figures();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.Examiners.PrimaryExaminer }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.Examiners.PrimaryExaminer createUsPatentGrantUsBibliographicDataGrantExaminersPrimaryExaminer() {
        return new UsPatentGrant.UsBibliographicDataGrant.Examiners.PrimaryExaminer();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.Examiners.AssistantExaminer }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.Examiners.AssistantExaminer createUsPatentGrantUsBibliographicDataGrantExaminersAssistantExaminer() {
        return new UsPatentGrant.UsBibliographicDataGrant.Examiners.AssistantExaminer();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.Assignees.Assignee.Addressbook.Address }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.Assignees.Assignee.Addressbook.Address createUsPatentGrantUsBibliographicDataGrantAssigneesAssigneeAddressbookAddress() {
        return new UsPatentGrant.UsBibliographicDataGrant.Assignees.Assignee.Addressbook.Address();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsParties.Agents.Agent.Addressbook.Address }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsParties.Agents.Agent.Addressbook.Address createUsPatentGrantUsBibliographicDataGrantUsPartiesAgentsAgentAddressbookAddress() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsParties.Agents.Agent.Addressbook.Address();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsParties.Inventors.Inventor.Addressbook.Address }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsParties.Inventors.Inventor.Addressbook.Address createUsPatentGrantUsBibliographicDataGrantUsPartiesInventorsInventorAddressbookAddress() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsParties.Inventors.Inventor.Addressbook.Address();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsParties.UsApplicants.UsApplicant.Residence }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsParties.UsApplicants.UsApplicant.Residence createUsPatentGrantUsBibliographicDataGrantUsPartiesUsApplicantsUsApplicantResidence() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsParties.UsApplicants.UsApplicant.Residence();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsParties.UsApplicants.UsApplicant.Addressbook.Address }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsParties.UsApplicants.UsApplicant.Addressbook.Address createUsPatentGrantUsBibliographicDataGrantUsPartiesUsApplicantsUsApplicantAddressbookAddress() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsParties.UsApplicants.UsApplicant.Addressbook.Address();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.RelatedPublication.DocumentId }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.RelatedPublication.DocumentId createUsPatentGrantUsBibliographicDataGrantUsRelatedDocumentsRelatedPublicationDocumentId() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.RelatedPublication.DocumentId();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.Continuation.Relation.ChildDoc.DocumentId }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.Continuation.Relation.ChildDoc.DocumentId createUsPatentGrantUsBibliographicDataGrantUsRelatedDocumentsContinuationRelationChildDocDocumentId() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.Continuation.Relation.ChildDoc.DocumentId();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.Continuation.Relation.ParentDoc.DocumentId }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.Continuation.Relation.ParentDoc.DocumentId createUsPatentGrantUsBibliographicDataGrantUsRelatedDocumentsContinuationRelationParentDocDocumentId() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsRelatedDocuments.Continuation.Relation.ParentDoc.DocumentId();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsFieldOfClassificationSearch.ClassificationNational }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsFieldOfClassificationSearch.ClassificationNational createUsPatentGrantUsBibliographicDataGrantUsFieldOfClassificationSearchClassificationNational() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsFieldOfClassificationSearch.ClassificationNational();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsReferencesCited.UsCitation.Nplcit }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsReferencesCited.UsCitation.Nplcit createUsPatentGrantUsBibliographicDataGrantUsReferencesCitedUsCitationNplcit() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsReferencesCited.UsCitation.Nplcit();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsReferencesCited.UsCitation.ClassificationNational }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsReferencesCited.UsCitation.ClassificationNational createUsPatentGrantUsBibliographicDataGrantUsReferencesCitedUsCitationClassificationNational() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsReferencesCited.UsCitation.ClassificationNational();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.UsReferencesCited.UsCitation.Patcit.DocumentId }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.UsReferencesCited.UsCitation.Patcit.DocumentId createUsPatentGrantUsBibliographicDataGrantUsReferencesCitedUsCitationPatcitDocumentId() {
        return new UsPatentGrant.UsBibliographicDataGrant.UsReferencesCited.UsCitation.Patcit.DocumentId();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.FurtherCpc.ClassificationCpc.CpcVersionIndicator }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.FurtherCpc.ClassificationCpc.CpcVersionIndicator createUsPatentGrantUsBibliographicDataGrantClassificationsCpcFurtherCpcClassificationCpcCpcVersionIndicator() {
        return new UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.FurtherCpc.ClassificationCpc.CpcVersionIndicator();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.FurtherCpc.ClassificationCpc.ActionDate }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.FurtherCpc.ClassificationCpc.ActionDate createUsPatentGrantUsBibliographicDataGrantClassificationsCpcFurtherCpcClassificationCpcActionDate() {
        return new UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.FurtherCpc.ClassificationCpc.ActionDate();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.FurtherCpc.ClassificationCpc.GeneratingOffice }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.FurtherCpc.ClassificationCpc.GeneratingOffice createUsPatentGrantUsBibliographicDataGrantClassificationsCpcFurtherCpcClassificationCpcGeneratingOffice() {
        return new UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.FurtherCpc.ClassificationCpc.GeneratingOffice();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.MainCpc.ClassificationCpc.CpcVersionIndicator }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.MainCpc.ClassificationCpc.CpcVersionIndicator createUsPatentGrantUsBibliographicDataGrantClassificationsCpcMainCpcClassificationCpcCpcVersionIndicator() {
        return new UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.MainCpc.ClassificationCpc.CpcVersionIndicator();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.MainCpc.ClassificationCpc.ActionDate }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.MainCpc.ClassificationCpc.ActionDate createUsPatentGrantUsBibliographicDataGrantClassificationsCpcMainCpcClassificationCpcActionDate() {
        return new UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.MainCpc.ClassificationCpc.ActionDate();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.MainCpc.ClassificationCpc.GeneratingOffice }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.MainCpc.ClassificationCpc.GeneratingOffice createUsPatentGrantUsBibliographicDataGrantClassificationsCpcMainCpcClassificationCpcGeneratingOffice() {
        return new UsPatentGrant.UsBibliographicDataGrant.ClassificationsCpc.MainCpc.ClassificationCpc.GeneratingOffice();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.ClassificationsIpcr.ClassificationIpcr.IpcVersionIndicator }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.ClassificationsIpcr.ClassificationIpcr.IpcVersionIndicator createUsPatentGrantUsBibliographicDataGrantClassificationsIpcrClassificationIpcrIpcVersionIndicator() {
        return new UsPatentGrant.UsBibliographicDataGrant.ClassificationsIpcr.ClassificationIpcr.IpcVersionIndicator();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.ClassificationsIpcr.ClassificationIpcr.ActionDate }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.ClassificationsIpcr.ClassificationIpcr.ActionDate createUsPatentGrantUsBibliographicDataGrantClassificationsIpcrClassificationIpcrActionDate() {
        return new UsPatentGrant.UsBibliographicDataGrant.ClassificationsIpcr.ClassificationIpcr.ActionDate();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.ClassificationsIpcr.ClassificationIpcr.GeneratingOffice }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.ClassificationsIpcr.ClassificationIpcr.GeneratingOffice createUsPatentGrantUsBibliographicDataGrantClassificationsIpcrClassificationIpcrGeneratingOffice() {
        return new UsPatentGrant.UsBibliographicDataGrant.ClassificationsIpcr.ClassificationIpcr.GeneratingOffice();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.ApplicationReference.DocumentId }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.ApplicationReference.DocumentId createUsPatentGrantUsBibliographicDataGrantApplicationReferenceDocumentId() {
        return new UsPatentGrant.UsBibliographicDataGrant.ApplicationReference.DocumentId();
    }

    /**
     * Create an instance of {@link UsPatentGrant.UsBibliographicDataGrant.PublicationReference.DocumentId }
     * 
     */
    public UsPatentGrant.UsBibliographicDataGrant.PublicationReference.DocumentId createUsPatentGrantUsBibliographicDataGrantPublicationReferenceDocumentId() {
        return new UsPatentGrant.UsBibliographicDataGrant.PublicationReference.DocumentId();
    }

}
